import React from 'react'
import ReactDOM from 'react-dom'

let Database = [
    {
        title: "Thor: God of Thunder / The Mighty Thor / Thor",
        writer: ["Aaron", "Jason Aaron"],
        artist: ["Esad Ribic and Russell Dauterman"],
        character: ["Thor", "Jane Foster", "Female Thor"],
        length: "Long",
        issues: ["Numerous Issues", "13 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "Jason Aaron's epic tale of Thor and Jane Foster. This saga involves Thor's grand battle with Malekith throughout the Nine Realms, while reconciling his position and idea of what a god should be, and for whom. \r\n ",
        run: "Modern"
    },
    {
        title: "Aquaman New 52",
        writer: ["Abnett", "Dan Abnett"],
        artist: ["Ivan Reis"],
        character: ["Aquaman", "Mera", "Ocean Master"],
        length: "Medium",
        issues: [],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Building off the previous volumes by Geoff Johns and Jeff Parker, ",
        run: "Modern"
    },
    {
        title: "Aquaman Rebirth",
        writer: ["Abnett", "Dan Abnett"],
        artist: ["Various"],
        character: ["Aquaman", "Mera", "Ocean Master"],
        length: "Long",
        issues: ["38 issues", "6 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Abnett continues his New 52 Aquaman into the Rebirth initiative, continuing to follow Arthur Curry and Mera to bridge the divide between the nations of Earth and Atlantis. \r\n ",
        run: "Modern"
    },
    {
        title: "Black Bolt",
        writer: ["Ahmed", "Saladin Ahmed"],
        artist: ["Christian Ward"],
        character: ["Black Bolt"],
        length: "Short",
        issues: ["12 issues", "2 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "Blackagar Boltagon finds him imprisoned and alone, with no idea how he got into this position. \r\n ",
        run: "Modern"
    },
    {
        title: "Daredevil",
        writer: ["Bendis", "Brian Bendis", "Brian Michael Bendis"],
        artist: ["Alex Maleev"],
        character: ["Daredevil", "Elektra", "Kingpin"],
        length: "Long",
        issues: ["65 issues", "3 omnibuses"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "Bendis' long running Daredevil run is a landmark series, showcasing Daredevil's fight to protect Hell's Kitchen while also battling the legal fight to protect his secret identity as Lawyer Matt Murdock",
        run: "Classic"
    },
    {
        title: "Infamous Iron Man",
        writer: ["Bendis", "Brian Bendis", "Brian Michael Bendis"],
        artist: ["Alex Maleev"],
        character: ["Doctor Doom", "Iron Heart"],
        length: "Short",
        issues: ["12 issues", "2 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "A significant different take on Doctor Doom, who wishes to turn away from his cold hearted past. He dons the Iron Man armor to do good, but endures doubt from friends and foes alike in the process \r\n ",
        run: "Modern"
    },
    {
        title: "The Immortal Iron Fist",
        writer: ["Brubaker", "Fraction", "Ed Brubaker", "Matt Fraction", "Ed Brubaker and Matt Fraction"],
        artist: ["David Aja"],
        character: ["Iron Fist", "Danny Rand"],
        length: "Short",
        issues: ["16 issues", "3 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Marvels",
        writer: ["Busiek", "Kurt Busiek"],
        artist: ["Alex Ross"],
        character: [""],
        length: "Short",
        issues: ["4 issues", "1 volume"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "This series brings the perspective about the emergence of the Marvel Universe and its superheroes and villains through the eyes of a journalist. From their first appearance to numerous more, the book documents his aging perspective and feelings. \r\n ",
        run: "Classic"
    },
    {
        title: "Venom",
        writer: ["Cates", "Donny Cates"],
        artist: ["Ryan Stegman"],
        character: ["Venom", "Carnage"],
        length: "",
        issues: [],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "A modern story of Eddie Brock and his symbiote. Writer Donny Cates expands the symbiote lore by explaining the history and connection of all symbiotes to their King Knull. \r\n ",
        run: "Ongoing"
    },
    {
        title: "DC: The New Frontier",
        writer: ["Cooke", "Darwyn Cooke"],
        artist: ["Darwyn Cooke"],
        character: [""],
        length: "Long",
        issues: [],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "A classical take on the history of the DC Universe, starting from World War II to the present. A more positive, uplifting retelling than other modern contemporaries of this scope. \r\n ",
        run: "Classic"
    },
    {
        title: "Marauders",
        writer: ["Duggan", "Gerry Duggan"],
        artist: ["Stefano Caselli"],
        character: ["Kitty Pryde", "Kate Pryde", "Storm", "Emma  Frost"],
        length: "",
        issues: [],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "Part of Hickman's Dawn of X initiative, Kate Pryde leads a group of mutants to fight for mutants who cannot or are unable to travel to the mutant homeland of Krakoa. \r\n ",
        run: "Ongoing"
    },
    {
        title: "The Wild Storm",
        writer: ["Ellis", "Warren Ellis"],
        artist: ["Jon Davis-Hunt"],
        character: ["Grifter", "Midnighter", "Apollo"],
        length: "Medium",
        issues: ["24 issues", "4 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "A modern retelling of the original Wild Storm Imprint characters. A warring planet Earth involving IO, those who hold dominance over the Earth, Skywatch, holding dominion over Space, and everyone in between who suffer by the hands of these two corporations. \r\n ",
        run: "Modern"
    },
    {
        title: "Transmetropolitan",
        writer: ["Ellis", "Warren Ellis"],
        artist: ["Darick Robertson"],
        character: [""],
        length: "Long",
        issues: [],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Planetary",
        writer: ["Ellis", "Warren Ellis"],
        artist: ["John Cassaday"],
        character: [""],
        length: "Medium",
        issues: ["27 issues", "4 volumes"],
        start: "",
        genre: "",
        company: ["DC Comics"],
        synopsis: "A fantastic story about self-proclaimed Archaeologists of History, who seek to know, understand and preserve the secrets of the world, while simultaenously paying respect to the medium of comic books as a whole. \r\n ",
        run: "Classic"
    },
    {
        title: "The Immortal Hulk",
        writer: ["Ewing", "Al Ewing"],
        artist: ["Joe Bennett"],
        character: ["Hulk"],
        length: "Long",
        issues: [""],
        start: "",
        genre: "Magic",
        company: "Marvel",
        synopsis: "A revolutionary take on the classic green hero, Al Ewing reinvents new and old to tell a cosmic horror story of the origins of the Hulk, his alter egos and the nature of Gamma radiation itself that intertwines friends and foes alike in the grand history of Bruce Banner. \r\n ",
        run: "Ongoing"
    },
    {
        title: "Sandman",
        writer: ["Gaiman", "Neil Gaiman"],
        artist: ["Various"],
        character: ["Dream", "Death"],
        length: "Long",
        issues: ["75 issues", "10 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Gaiman's legendary tale of Dream, who after released from imprisonment for 70 years, seeks to reclaim and understand his old kingdom. \r\n ",
        run: "Classic"
    },
    {
        title: "Marvel 1602",
        writer: ["Gaiman", "Neil Gaiman"],
        artist: ["Andy Kubert"],
        character: [""],
        length: "Short",
        issues: ["8 issues"],
        start: "",
        genre: "",
        company: "Marvel Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "The Eternals",
        writer: ["Gaiman", "Neil Gaiman"],
        artist: ["John Romita Jr."],
        character: [""],
        length: "Short",
        issues: ["7 issues"],
        start: "",
        genre: "",
        company: "Marvel Comics",
        synopsis: "A modern re-introduction of Jack Kirby's Eternals, who have been dormant on Earth for an extended period of time for reasons currently unknown. \r\n ",
        run: "Modern"
    },
    {
        title: "East of West",
        writer: ["Hickman", "Jonathan Hickman"],
        artist: ["Nick Dragotta"],
        character: [""],
        length: "Long",
        issues: ["45 issues", "10 volumes"],
        start: "",
        genre: "",
        company: "Image",
        synopsis: "An alternate steampunk history of America and seven nations, who reconcile with prophecies foretelling the Apocalypse, further exacerbated by the Four Horsemen, who unwaveringly seek out this goal. \r\n ",
        run: "Modern"
    },
    {
        title: "Avengers / New Avengers / Secret Wars",
        writer: ["Hickman", "Jonathan Hickman"],
        artist: ["Various"],
        character: ["Captain America", "Steve Rogers", "Iron Man", "Tony Stark", "Black Panther", "Doctor Strange", "Stephen Strange", "Namor", "Mister Fantastic", "Mr. Fantastic", "Mr Fantastic", "Reed Richards", "Black Bolt", "Blackagar Boltagon"],
        length: "Long",
        issues: ["Numerous Issues", "15 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "A critically acclaimed long running story of the Avengers fighting a multiversal threat that they presently cannot understand, and will push them to the brink of their moral and psychological limits. \r\n",
        run: "Modern"
    },
    {
        title: "House of X / Powers of X",
        writer: ["Hickman", "Jonathan Hickman"],
        artist: ["Pepe Larraz and R.B. Silva"],
        character: ["Wolverine", "Jean Grey", "Cyclops", "Storm", "Professor X", "Magneto", "Moira McTaggert", "Professor Xavier", "Xavier", "Nightcrawler", "Emma Frost"],
        length: "Long",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "The beyond exceptional new start for the X-Men, spearheaded by visionary Jonathan Hickman. Preceding numerous new X-men titles is this limited series duology that sets the new foundation for the X-men, their homeland of Krakoa, and how it came to be. \r\n ",
        run: "Modern"
    },
    {
        title: "X-Men",
        writer: ["Hickman", "Jonathan Hickman"],
        artist: ["Francis Leinil Yu"],
        character: ["Wolverine", "Jean Grey", "Cyclops", "Storm", "Professor X", "Magneto", "Moira McTaggert", "Professor Xavier", "Xavier", "Nightcrawler", "Emma Frost"],
        length: "Long",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "The mainline title in the Dawn of X initiative, focusing on the politics and development of Krakoa, the mutant nation that seeks legitimacy and respect worldwide. \r\n ",
        run: "Ongoing"
    },
    {
        title: "Inhumans",
        writer: ["Jenkins", "Paul Jenkins"],
        artist: ["Jae Lee"],
        character: ["Black Bolt", "Medusa", "Maximus"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "nA",
        run: "Classic"
    },
    {
        title: "The Sentry",
        writer: ["Jenkins", "Paul Jenkins"],
        artist: ["Jae Lee"],
        character: ["Sentry"],
        length: "Short",
        issues: ["5 issues"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "nA",
        run: "Modern"
    },
    {
        title: "Aquaman New 52",
        writer: ["Johns", "Geoff Johns"],
        artist: ["Ivan Reis"],
        character: ["Aquaman", "Mera", "Ocean Master"],
        length: "Medium",
        issues: [],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "A modern reboot involves Aquaman and Mera combatting threats from both outside and within the Kingdom of Atlantis, particularly Arthur's brother, Ocean Master. \r\n ",
        run: "Modern"
    },
    {
        title: "Justice League New 52",
        writer: ["Johns", "Geoff Johns"],
        artist: ["Various"],
        character: ["Superman", "Batman", "Wonder Woman", "Cyborg", "Aquaman", "Green Lantern", "Hal Jordan", "Jessica Cruz", "Simon Baz", "Lex Luthor"],
        length: "Long",
        issues: ["50 issues", "8 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "A brand new introduction and set of foes for the formation of the Justice League and their ongoing battles to protect planet Earth from vicious adversaries. \r\n ",
        run: "Modern"
    },
    {
        title: "Green Lantern",
        writer: ["Johns", "Geoff Johns"],
        artist: ["Various"],
        character: ["Green Lantern", "Hal Jordan", "Simon Baz", "John Stewart", "Kyle Rayner", "Guy Gardner", "Parallax", "Sinestro", "Kilowog"],
        length: "Long",
        issues: [],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Geoff John's magnum opus in returning Hal Jordan to the DC Universe, while simultaenously expanding and exploring all facets of the cosmic aspects of the Lantern universe. \r\n ",
        run: "Classic"
    },
    {
        title: "Forever Evil",
        writer: ["Johns", "Geoff Johns"],
        artist: ["David Finch"],
        character: ["Batman", "Lex Luthor"],
        length: "Short",
        issues: ["7 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "When the Crime Syndicate of Earth-3 invades the Prime Earth, and all the superheroes are incapacitated, it's up to the villains to rise up. \r\n ",
        run: "Modern"
    },
    {
        title: "Flashpoint",
        writer: ["Johns", "Geoff Johns"],
        artist: ["Andy Kubert"],
        character: ["Flash", "Batman"],
        length: "Short",
        issues: ["5 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "When Barry Allen goes back in time to save his mother at the hands of the Reverse Flash, he unexpectedly creates a new alternate reality with new friends and foes. \r\n ",
        run: "Modern"
    },
    {
        title: "Doomsday Clock",
        writer: ["Johns", "Geoff Johns"],
        artist: ["Gary Frank"],
        character: ["Batman", "Bruce Wayne", "Superman", "Clark Kent", "Lois Lane", "Doctor Manhattan", "Dr Manhattan", "Manhattan", "Rorschach", "Comedian", "Ozymandias", "Adrian Veidt", "Veidt"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "The maxi-series that explains the introduction of the Watchmen characters into the main DC Universe. \r\n ",
        run: "Modern"
    },
    {
        title: "The Omega Men",
        writer: ["King", "Tom King"],
        artist: ["Barnaby Bagenda and Toby Cypress"],
        character: ["Kyle Rayner"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Tom King brings us a fascinating new take on the White Lantern, Kyle Rayner. Stranded in a estranged solar system with the planets embroiled in a civil war, Rayner must work towards peace while navigating the morally grey, savage characters involved.\r\n ",
        run: "Classic"
    },
    {
        title: "Grayson",
        writer: ["King", "Tom King"],
        artist: ["Mikel Janin"],
        character: ["Dick Grayson", "Nightwing"],
        length: "Medium",
        issues: ["20 issues", "5 Volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "A radically different take on Dick Grayson, aka Nightwing, who joins Spiral and focuses his efforts on taking down the secret spy organizations of the underground world. \r\n ",
        run: "Modern"
    },
    {
        title: "Vision",
        writer: ["King", "Tom King"],
        artist: ["Gabriel Hernandez Walta"],
        character: ["Vision", "Scarlet Witch"],
        length: "Short",
        issues: ["12 issues", "2 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "When Vision decides to create a family for himself, he becomes wrapped up in the demands of being an Avenger and the expectations of being a father to his family. \r\n",
        run: "Classic"
    },
    {
        title: "Mister Miracle",
        writer: ["King", "Tom King"],
        artist: ["Mitch Gerads"],
        character: ["Darkseid", "Orion", "Mister Miracle", "Big Barda", "Furies", "Granny Goodness"],
        length: "Short",
        issues: ["12 issues", '1 volume'],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Scott Free becomes unhinged, and is unable to differentiate dream from reality in this absurd tale of war between New Genesis and Apokolips. \r\n\ ",
        run: "Classic"
    },
    {
        title: "Rorschach",
        writer: ["King", "Tom King"],
        artist: ["Jorge Fornes"],
        character: ["Rorscach"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "nA",
        run: "Ongoing"
    },
    {
        title: "Strange Adventures",
        writer: ["King", "Tom King"],
        artist: ["Mitch Gerads and Evan Shaner"],
        character: ["Adam Strange"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "nA",
        run: "Ongoing"
    },
    {
        title: "Batman Rebirth",
        writer: ["King", "Tom King"],
        artist: ["Various"],
        character: ["Batman"],
        length: "Long",
        issues: ["87 issues", "10 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Batman squares off against Bane in this length series, where Bane seeks to break the Bat both physically and psychologically. \r\n\ ",
        run: "Modern"
    },
    {
        title: "Green Arrow",
        writer: ["Lemire", "Jeff Lemire"],
        artist: ["Andrea Sorrentino"],
        character: ["Green Arrow"],
        length: "Medium",
        issues: [],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "nA",
        run: "Modern"
    },
    {
        title: "Animal Man",
        writer: ["Lemire", "Jeff Lemire"],
        artist: ["Travel Foreman"],
        character: ["Animal Man"],
        length: "Medium",
        issues: ["29 issues", "5 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "nA",
        run: "Modern"
    },
    {
        title: "Essex County",
        writer: ["Lemire", "Jeff Lemire"],
        artist: ["Jeff Lemire"],
        character: [""],
        length: "Medium",
        issues: [],
        start: "",
        genre: "",
        company: "Other",
        synopsis: "Lemire pens a emotional, heartful story about rural Canadians that is heavily inspired by his own childhood. \r\n ",
        run: "Modern"
    },
    {
        title: "Moon Knight",
        writer: ["Lemire", "Jeff Lemire"],
        artist: ["Various"],
        character: ["Moon Knight"],
        length: "Short",
        issues: ["14 issues", "3 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "The titular character seeks to find peace and balance between his conflicting personalities in order to be rid of his connection to Konshu. \r\n ",
        run: "Modern"
    },
    {
        title: "Descender",
        writer: ["Lemire", "Jeff Lemire"],
        artist: ["Dustin Nguyen"],
        character: [""],
        length: "Long",
        issues: ["32 issues", "6 volumes"],
        start: "",
        genre: "",
        company: "Image",
        synopsis: "nA",
        run: "Modern"
    },
    {
        title: "Black Hammer",
        writer: ["Lemire", "Jeff Lemire"],
        artist: ["Dean Ormston"],
        character: [""],
        length: "",
        issues: [],
        start: "",
        genre: "",
        company: "Other",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Gideon Falls",
        writer: ["Lemire", "Jeff Lemire"],
        artist: ["Andrea Sorrentino"],
        character: [""],
        length: "Medium",
        issues: [],
        start: "",
        genre: "",
        company: "Image",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Red Hood and the Outlaws Rebirth",
        writer: ["Lobdell", "Scott Lobdell"],
        artist: ["Dexter Soy"],
        character: ["Red Hood", "Jason Todd", "Artemis", "Bizarro"],
        length: "Long",
        issues: ["50 issues", "8 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Flash Forward",
        writer: ["Lobdell", "Scott Lobdell"],
        artist: ["Brett Booth"],
        character: ["Flash", "Wally West"],
        length: "Short",
        issues: ["6 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Batman: The Long Halloween",
        writer: ["Loeb", "Jeph Loeb"],
        artist: ["Tim Sale"],
        character: ["Batman", "Harvey Dent"],
        length: "Short",
        issues: ["14 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Spider-Man: Blue",
        writer: ["Loeb", "Jeph Loeb"],
        artist: ["Tim Sale"],
        character: ["Spider-Man", "Spiderman"],
        length: "Short",
        issues: ["14 issues"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "The Dark Knight Returns",
        writer: ["Miller", "Frank Miller"],
        artist: ["Frank Miller"],
        character: ["Batman"],
        length: "Short",
        issues: ["4 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Batman: Year One",
        writer: ["Miller", "Frank Miller"],
        artist: ["David Mazzucchelli"],
        character: ["Batman"],
        length: "Short",
        issues: ["4 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Saga of the Swamp Thing",
        writer: ["Moore", "Alan Moore"],
        artist: ["Stephen Bissette"],
        character: ["Swamp Thing", "Abby Arcane", "Spectre", "Anton Arcane", "John Constantine", "Constantine"],
        length: "Long",
        issues: ["45 issues", "6 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Batman: The Killing Joke",
        writer: ["Moore", "Alan Moore"],
        artist: ["Brian Bolland"],
        character: ["Batman", "Joker"],
        length: "Short",
        issues: ["4 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Superman: Whatever Happened to the Man of Tomorrow?",
        writer: ["Moore", "Alan Moore"],
        artist: ["Various"],
        character: ["Superman", "Clark Kent", "Lois Lane"],
        length: "Short",
        issues: ["4 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Promethea",
        writer: ["Moore", "Alan Moore"],
        artist: ["J. H. Williams III"],
        character: ["Promethea"],
        length: "Medium",
        issues: ["24 issues", "5 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Watchmen",
        writer: ["Moore", "Alan Moore"],
        artist: ["Dave Gibbons", "Gibbons"],
        character: ["Doctor Manhattan", "Dr Manhattan", "Manhattan", "Rorschach", "Silk Spectre", "Nite Owl", "Comedian", "Ozymandias", "Adrian Veidt", "Veidt"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Miracleman",
        writer: ["Moore", "Alan Moore"],
        artist: ["Various"],
        character: ["Miracle Man", "Miracleman", "Miracle-Man", "Marvelman", "Marvel Man"],
        length: "Medium",
        issues: ["16 issues", "3 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "A deconstructionist take on the Billy Batson / Shazam archetype, where a young boy unlocked the powers of a superhero by uttering a special phrase. Moore takes on a darker.\r\n  ",
        run: "Classic"
    },
    {
        title: "V for Vendetta",
        writer: ["Moore", "Alan Moore"],
        artist: ["David Lloyd"],
        character: ["V", "Evie"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Moore brings another classic where he introduces the titular character V, who embraces anarchistic ideals to fight against the Totalitarian UK regime in a dystopian semi-futuristic world.\r\n ",
        run: "Classic"
    },
    {
        title: "X-Force",
        writer: ["Percy", "Benjamin Percy"],
        artist: ["Joshua Cassara"],
        character: ["Wolverine", "Domino", "Colossus", "Beast"],
        length: "",
        issues: [],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "",
        run: "Ongoing"
    },
    {
        title: "Green Arrow Rebirth",
        writer: ["Percy", "Ben Percy", "Benjamin Percy"],
        artist: ["Otto Schmidt and Juan Ferreyra"],
        character: ["Green Arrow", "Red Arrow", "Black Canary"],
        length: "Long",
        issues: ["38 issues", "6 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "With Rebirth returning to their roots, Benjamin Percy unveils the classic joke-quipping Green Arrow / Oliver Queen alongside Black Canary to defend Star City.\r\n ",
        run: "Modern"
    },
    {
        title: "Black Panther",
        writer: ["Priest", "Christopher Priest"],
        artist: ["Joe Bennett", "Bennett"],
        character: ["Black Panther", "Tchalla", "T'Challa", "Shuri", "Everett Ross"],
        length: "Long",
        issues: [],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Deathstroke",
        writer: ["Priest", "Christopher Priest"],
        artist: ["Joe Bennett", "Bennett"],
        character: ["Deathstroke", "Doctor Light", "Jericho", "Wintergreen", "Rose", "Rose Wilson", "Power Girl"],
        length: "Long",
        issues: ["50 issues", "8 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "The Rebirth run of Deathstroke possesses Priest's complex, non-linear storytelling that makes this run a dedicated read. The reader will explore Slade Wilson's attempts and mistakes to bring his family closer together. While difficult to follow and re-reads are expected, it is an excellent run that deserves your attention and respect.\r\n ",
        run: "Modern"
    },
    {
        title: "Exit Stage Left: The Snagglepuss Chronicles",
        writer: ["Russell", "Mark Russell"],
        artist: ["Mike Feehan and Mark Morales"],
        character: [""],
        length: "Short",
        issues: ["7 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "The Flintstones",
        writer: ["Russell", "Mark Russell"],
        artist: ["Steve Pugh"],
        character: [""],
        length: "Short",
        issues: ["12 issues"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Swamp Thing New 52",
        writer: ["Snyder", "Scott Snyder", "Soule", "Charles Soule"],
        artist: ["Yannick Paquette"],
        character: ["Swamp Thing", "Abby Arcane", "Spectre", "Anton Arcane"],
        length: "Long",
        issues: ["40 issues", "7 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Batman",
        writer: ["Snyder", "Scott Snyder"],
        artist: ["Greg Capullo"],
        character: ["Batman"],
        length: "Long",
        issues: ["52 issues", "10 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Dark Knights: Metal",
        writer: ["Snyder", "Scott Snyder"],
        artist: ["Greg Capullo"],
        character: ["Batman", "Superman", "Wonder Woman", "Cyborg", "Green Lantern", "Flash", "Aquaman"],
        length: "Short",
        issues: ["6 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Daredevil",
        writer: ["Soule", "Charles Soule"],
        artist: ["Greg Capullo"],
        character: ["Daredevil"],
        length: "Long",
        issues: ["8 volumes"],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "John Constantine: Hellblazer",
        writer: ["Spurrier", "Simon Spurrier"],
        artist: ["Various"],
        character: ["Constantine", "John Constantine", "Hellblazer"],
        length: "Short",
        issues: ["12 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Batman and Robin",
        writer: ["Tomasi", "Peter Tomasi", "Peter J Tomasi", "Peter J. Tomasi"],
        artist: ["Patrick Gleason"],
        character: ["Batman", "Robin", "Damian"],
        length: "Long",
        issues: ["40 issues", "7 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Superman Rebirth",
        writer: ["Tomasi", "Peter Tomasi", "Peter J Tomasi", "Peter J. Tomasi"],
        artist: ["Patrick Gleason"],
        character: ["Superman", "Jon Kent", "Jon", "Superboy"],
        length: "Long",
        issues: ["45 issues", "7 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Tomasi reboots the Superman series with a classic Clark Kent, who acts as both the hero of Metropolis as well as husband and father to Lois Lane and Jon Kent. This series brings the heartful moments of Superman to the forefront, where he navigates a world that is slightly alien to him, as well as trying his best to raise his son to be the best he can be.\r\n ",
        run: "Modern"
    },
    {
        title: "Super Sons",
        writer: ["Tomasi", "Peter Tomasi", "Peter J Tomasi", "Peter J. Tomasi"],
        artist: ["Patrick Gleason"],
        character: ["Robin", "Damian Wayne", "Damian", "Superboy", "Super Boy", "Jon Kent"],
        length: "Short",
        issues: ["18 issues", "3 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Detective Comics Rebirth",
        writer: ["Tynion", "James Tynion IV", "James Tynion", "Tynion IV"],
        artist: ["Various"],
        character: ["Batman", "Red Robin", "Orphan", "Spoiler", "Sandman", "Batwoman", "Batwing"],
        length: "Long",
        issues: ["47 issues", "7 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Tynion focuses on Batman introducing a team of superheroes to combat a multitude of threats that arise from close companions to futuristic threats.\r\n ",
        run: "Modern"
    },
    {
        title: "Justice League: Dark",
        writer: ["Tynion", "Tynion IV", "James Tynion", "James Tynion IV"],
        artist: ["Various"],
        character: ["Wonder Woman", "Constantine", "Zatanna", "Man Bat", "Man-Bat", "Swamp Thing", "Alec Holland", "Constantine", "John Constantine", "Hellblazer"],
        length: "Long",
        issues: ["28 issues", "5 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Saga",
        writer: ["Vaughan", "Brian Vaughan", "Brian K Vaughan", "Brian K. Vaughan"],
        artist: ["Fiona Staples"],
        character: [""],
        length: "Long",
        issues: [],
        start: "",
        genre: "",
        company: "Image",
        synopsis: "",
        run: "Ongoing"
    },
    {
        title: "Y: The Last Man",
        writer: ["Vaughan", "Brian Vaughan", "Brian K Vaughan", "Brian K. Vaughan"],
        artist: ["Pia Guerra"],
        character: [""],
        length: "Long",
        issues: ["60 issues", "10 volumes"],
        start: "",
        genre: "",
        company: ["DC Comics"],
        synopsis: "",
        run: "Classic"
    },
    {
        title: "Hal Jordan and the Green Lantern Corps",
        writer: ["Venditti", "Robert Venditti"],
        artist: ["Various"],
        character: ["Green Lantern", "Hal Jordan", "Simon Baz", "John Stewart", "Kyle Rayner", "Guy Gardner", "Parallax", "Sinestro", "Kilowog"],
        length: "Long",
        issues: ["50 issues", "7 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "Continuing off his Green Lantern New 52 run, Robert Venditti spearheads the new Green Lantern Rebirth series focusing on Hal Jordan and his close allies, John Stewart, Guy Gardner and Kyle Rayner. The Rebirth series returns to their roots with the rise of Sinestro and the Yellow Lanterns, the Dominators and other threats.\r\n ",
        run: "Modern"
    },
    {
        title: "Kingdom Come",
        writer: ["Waid", "Mark Waid"],
        artist: ["Alex Ross"],
        character: [""],
        length: "Short",
        issues: ["4 issues", "1 volume"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Classic"
    },
    {
        title: "New Super-Man",
        writer: ["Yang", "Gene Yang", "Luen Yang", "Gene Luen Yang"],
        artist: ["Viktor Bogdanovic"],
        character: ["New Super Man", "New Super-Man", "New Superman"],
        length: "Medium",
        issues: ["24 issues", "4 volumes"],
        start: "",
        genre: "",
        company: "DC Comics",
        synopsis: "",
        run: "Modern"
    },
    {
        title: "Daredevil",
        writer: ["Zdarsky", "Chip Zdarsky"],
        artist: ["Various"],
        character: ["Daredevil", "Elektra", "Kingpin"],
        length: "",
        issues: [],
        start: "",
        genre: "",
        company: "Marvel",
        synopsis: "While in a weakened state, Matt Murdock as Daredevil mistakenly kills a criminal one evening. In doing so, he must come to terms with the idea and impact that the both the superhero and the idea of Daredevil has on the community of Hell's Kitchen. Embroiled in that internal debate are longtime enemies of Daredevil, as well as new corporate CEO's hoping to takeover.\r\n ",
        run: "Ongoing"
    },
];

export default Database
